# Generated by Django 5.1.5 on 2025-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('time_period', models.CharField(blank=True, max_length=50, null=True)),
                ('stipend', models.CharField(blank=True, max_length=50, null=True)),
                ('internship_link', models.URLField()),
            ],
        ),
    ]
